#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : sphinx-last-updated-by-git
Version  : 0.3.0
Release  : 2
URL      : https://files.pythonhosted.org/packages/d0/c8/298fecaaaceb96ca89cb41d548b3c57c4e7305f3a08543312a548414373f/sphinx-last-updated-by-git-0.3.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/d0/c8/298fecaaaceb96ca89cb41d548b3c57c4e7305f3a08543312a548414373f/sphinx-last-updated-by-git-0.3.0.tar.gz
Summary  : Get the "last updated" time for each Sphinx page from Git
Group    : Development/Tools
License  : BSD-2-Clause
Requires: sphinx-last-updated-by-git-python = %{version}-%{release}
Requires: sphinx-last-updated-by-git-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(sphinx)

%description
=========================================================
        
        This is a little Sphinx_ extension that does exactly that.
        It also checks for included files and other dependencies and
        uses their "last updated" time if it's more recent.
        
        If a page doesn't have a source file, its last_updated_ time is set to ``None``.
        
        The default value for html_last_updated_fmt_ is changed
        from ``None`` to the empty string.
        
        Usage
            #. Install the Python package ``sphinx-last-updated-by-git``
            #. Add ``'sphinx_last_updated_by_git'`` to ``extensions`` in your ``conf.py``
            #. Run Sphinx!
        
        Options
            * If a source file is not tracked by Git (e.g. because it has been
              auto-generated on demand by autosummary_generate_) but its dependencies
              are, the last_updated_ time is taken from them.  If you don't want this
              to happen, use ``git_untracked_check_dependencies = False``.
        
            * If a source file is not tracked by Git, its HTML page doesn't get a
              source link.  If you do want those pages to have a sourcelink, set
              ``git_untracked_show_sourcelink = True``.  Of course, in this case
              html_copy_source_ and html_show_sourcelink_ must also be ``True``, and
              the theme you are using must support source links in the first place.
        
            * By default, timestamps are displayed using the local time zone.
              You can specify a datetime.timezone_ object (or any ``tzinfo`` subclass
              instance) with the configuration option ``git_last_updated_timezone``.
              You can also use any string recognized by babel_,
              e.g.  ``git_last_updated_timezone = 'NZ'``.
        
            * By default, the "last updated" timestamp is added as an HTML ``<meta>``
              tag.  This can be disabled by setting the configuration option
              ``git_last_updated_metatags`` to ``False``.
        
        Caveats
            * When using a "Git shallow clone" (with the ``--depth`` option),
              the "last updated" commit for a long-unchanged file
              might not have been checked out.
              In this case, the last_updated_ time is set to ``None``
              (and a warning is shown during the build).

%package python
Summary: python components for the sphinx-last-updated-by-git package.
Group: Default
Requires: sphinx-last-updated-by-git-python3 = %{version}-%{release}

%description python
python components for the sphinx-last-updated-by-git package.


%package python3
Summary: python3 components for the sphinx-last-updated-by-git package.
Group: Default
Requires: python3-core
Provides: pypi(sphinx_last_updated_by_git)
Requires: pypi(sphinx)

%description python3
python3 components for the sphinx-last-updated-by-git package.


%prep
%setup -q -n sphinx-last-updated-by-git-0.3.0
cd %{_builddir}/sphinx-last-updated-by-git-0.3.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1637350805
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
